import type { Metadata } from "next";
import "&/styles/globals.css";
import { Pathname } from "./pathname";
import { Header } from "&/components/layout/Header";
import SideNavBar from "&/components/layout/SideNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang="en" className="bg-gray-50">
      <Pathname>
        <Header />
        <SideNavBar />
        {children}
      </Pathname>
    </html>
  );
}
