import type { Metadata } from "next";
import "&/styles/globals.css";
import SideNav from "&/components/SideNav";
import { Pathname } from "./pathname";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  console.log(params);

  return (
    <html lang="en">
      <Pathname>
        <SideNav />
        {children}
      </Pathname>
    </html>
  );
}
